# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04 # Using a recent stable Ubuntu version
  tools:
    python: "3.10" # Using a stable Python version, not the bleeding edge

sphinx:
  configuration: conf.py # Tells Sphinx the name of the config file
  conf_dir: docs/
  builder: html
  fail_on_warning: true


python:
  install:
    - method: pip
      path: . # If your main project needs to be installed for autodoc
    - requirements: docs/requirements.txt # Optional: For documentation-specific Python dependencies
